/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details take a look at the Building C++ applications and libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.5.1/userguide/building_cpp_projects.html
 */

plugins {
    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`

    //id("org.bitbucket.akornilov.cpp-build-tuner") version "0.7"
    id("loggersoft.cpp-ide-generator") version "0.5"
}

// Set the target operating system and architecture for this application
application {
    targetMachines.add(machines.linux.x86_64)
}

ide { // configure<loggersoft.gradle.cpp.idegenerator.ConfigExtension>{
    // autoGenerate = true // Cannot access: it is private in 'ConfigExtension'
    // setAutoGenerate(true) // Does not seem to work
    setQtCreator(true)
}


